import javafx.util.Pair;

import java.lang.reflect.Array;
import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        // GetItemList
        List<Item> itemList = this.itemRepository.findAll();
        // output the title
        System.out.println("============= Order details =============");
        // Get the sumPrice and all items
        int sumPrice = 0;
        Map<String, Pair<Item, Integer>> sumItemMap = new HashMap<String, Pair<Item, Integer>>();
        // output the item
        for(String input : inputs) {
            // split nowItem to id and count
            String[] nowItem = input.split(" x ");
            String nowItemId = nowItem[0];
            int nowItemCount = Integer.parseInt(nowItem[1]);
            // find the item of sameId
            for(Item item : itemList) {
                // find the same item
                if(item.getId().equals(nowItemId)) {
                    // add the price
                    int itemPrice = (int)item.getPrice() * nowItemCount;
                    sumPrice += (int)item.getPrice() * nowItemCount;
                    // save the item
                    sumItemMap.put(item.getId(), new Pair<>(item, nowItemCount));
                    // output this item
                    System.out.format("%s x %s = %d yuan\n", item.getName(), nowItemCount, itemPrice);
                    break;
                }
            }
        }
        // output the split line
        System.out.println("-----------------------------------");
        // output the Promotion used
        List<SalesPromotion> promotionList = this.salesPromotionRepository.findAll();
        System.out.println("Promotion used:");
        for(SalesPromotion promotion : promotionList) {
            switch (promotion.getType()) {
                case "BUY_30_SAVE_6_YUAN":
                    if(sumPrice >= 30){
                        System.out.println(promotion.getDisplayName());
                    }
                    break;
                case "50%_DISCOUNT_ON_SPECIFIED_ITEMS":
                    // get the sale items
                    List<String> promotionItems = promotion.getRelatedItems();
                    // the sale price
                    int savingPrice = 0, minCount = Integer.MAX_VALUE;
                    // the break flag
                    boolean breakFlag = false;
                    for(String promotionItem : promotionItems) {
                        Pair<Item, Integer> item = sumItemMap.get(promotionItem);
                        if(item == null) {
                            breakFlag = true;
                            break;
                        }
                        savingPrice += item.getKey().getPrice();
                        minCount = Math.min(minCount, item.getValue());
                    }
                    System.out.format("%s(%s)，saving %d yuan\n", promotion.getDisplayName(), String.join(",", promotion.getRelatedItems()), savingPrice * minCount);
                    break;
            }
        }
        // output the split line
        System.out.println("-----------------------------------");
        // output the sumPrice
        System.out.format("Total: %d yuan\n", sumPrice);
        // output the end line
        System.out.println("===================================");
        return null;
    }
}
